### PR TITLE
Fix issues with registries

### LINKED ISSUE #370: Unable to parse WWW-Authenticate header from Harbor registry
## Description

When connecting to a Harbor registry via Generic Registry V2, the extension fails with:

```
Unable to parse WWW-Authenticate header: "Basic realm="harbor""
```

## Steps to Reproduce

1. Connect Registry -> Generic Registry V2
2. Enter Harbor URL (e.g., `https://harbor.example.com`)
3. Enter valid username/password (same credentials work with `docker login`)
4. Error appears in the registry tree view

## Expected Behavior

The extension should authenticate and list repositories from the Harbor registry.

## Actual Behavior

The extension fails to parse the `WWW-Authenticate` header returned by Harbor.

Harbor returns:
```
WWW-Authenticate: Basic realm="harbor"
```

## Additional context

- Our harbor instance is protected by Keycloak
- I use the CLI Secret provided in Harbor - User Profile, which works in docker CLI
- ms-azuretools.vscode-containers version v2.4.0

### LINKED ISSUE #435: RequestInit: duplex option is required when sending a body
Type: <b>Bug</b>

When drilling into the Azure Registry - on a published container - This error occurs:

RequestInit: duplex option is required when sending a body

Duplex needs to be set to half it seems.

Extension version: 2.4.1
VS Code version: Code 1.113.0 (cfbea10c5ffb233ea9177d34726e6056e89913dc, 2026-03-24T15:07:18+01:00)
OS version: Windows_NT x64 10.0.26200
Modes:

App Host: desktop
Remote Name: undefined
Language: en

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) Ultra 7 268V (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>GPU0: VENDOR= 0x8086, DEVICE=0x64a0 [Intel(R) Arc(TM) 140V GPU (16GB)], DRIVER_VENDOR=Intel, DRIVER_VERSION=32.0.101.6737 *ACTIVE*<br>GPU1: VENDOR= 0x1414, DEVICE=0x008c [Microsoft Basic Render Driver], DRIVER_VERSION=10.0.26100.7309<br>Machine model name: <br>Machine model version: <br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (8.59GB free)|
|Process Argv|--crash-reporter-id 55c1fb58-2735-461d-bf0f-31642642e24a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
binariesv615:30325510
nativeloc1:31344060
dwcopilot:31170013
471b6256:31263136
dwoutputs:31242946
copilot_t_ci:31333650
e5gg6876:31282496
pythonrdcb7:31342333
6518g693:31463988
aj953862:31281341
6abeh943:31336334
envsactivate1:31464700
cloudbuttont:31379625
aihoversummaries_f:31469309
3efgi100_wstrepl:31403338
55ia6109:31457054
use-responses-api:31390855
defaultusage:31403421
ddidtcf:31399634
je187915:31401257
ec5jj548:31422691
cmp-cht-xtab-300-edit-0-7-speculative:31484964
metis_rerank_treatment1:31422731
cp_cls_c_966_ss:31454199
4je02754:31466945
find_all_ref_in_bg_f:31469307
8hhj4413:31478653
ge8j1254_inline_auto_hint_haiku:31431912
8g5ec713_opus_4_6:31486023
cp_cls_c_1081:31454833
conptydll_false:31485576
ia-use-proxy-models-svc:31452481
e9c30283:31461165
test_treatment2:31471001
control_6dc23131:31467998
idci7584:31464702
nes-ftch-new:31485413
showingstats:31481873
534a6447_copy:31478748
nes-extended-on:31455476
chat:31457767
8hig5102:31480529
67jbj424:31486320
bg_compact_c:31481651
t-some:31486549
cpptoolson-v2:31475363
db0gd219:31481871
23c7c724:31484514
po_com_t:31486091
ddid_t:31478206

```

</details>

### LINKED ISSUE #440: Sonatype Nexus On-premise (local docker registry) Connectivity Error
Type: <b>Bug</b>

Hello, bro!

I can't using my local Sonatype Nexus.
Error: Unable to parse WWW-Authenticate header: "BASIC realm="Sonatype Nexus Repository Manager""

Please fix it.

Thank you so much!

Best regards, Vladimir

Extension version: 2.4.1
VS Code version: Code 1.115.0 (41dd792b5e652393e7787322889ed5fdc58bd75b, 2026-04-07T22:04:57Z)
OS version: Windows_NT x64 10.0.26200
Modes:

App Host: desktop
Remote Name: undefined
Language: en

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>GPU0: VENDOR= 0x1ab8, DEVICE=0x4005 [Parallels Display Adapter (WDDM)], DRIVER_VENDOR=0x00001AB8, DRIVER_VERSION=20.18.2630.57392 *ACTIVE*<br>GPU1: VENDOR= 0x1414, DEVICE=0x008c [Microsoft Basic Render Driver], DRIVER_VERSION=10.0.26100.8115<br>Machine model name: <br>Machine model version: <br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>trees_in_viz: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.98GB (1.50GB free)|
|Process Argv|--crash-reporter-id 5f1ee2b9-dfb7-4530-8267-da8838f5800b|
|Screen Reader|no|
|VM|50%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
binariesv615:30325510
nativeloc1:31344060
dwcopilot:31170013
dwoutputs:31242946
copilot_t_ci:31333650
e5gg6876:31282496
pythonrdcb7:31342333
6518g693:31463988
aj953862:31281341
4f60g487:31327383
6abeh943:31336334
envsactivate1:31464700
cloudbuttont:31379625
3efgi100_wstrepl:31403338
use-responses-api:31390855
ec5jj548:31422691
cp_cls_c_966_ss:31454199
a9239246:31485761
4je02754:31466945
8hhj4413:31478653
cp_cls_c_1081:31454833
conptydll_true:31489736
e9c30283:31461165
test_treatment2:31471001
idci7584:31464702
3bj34942:31489864
534a6447_copy:31478748
chat:31457767
t-some:31486549
cpptoolsoff-v2:31475362
ec1eg703:31488002
ddid_t:31478206
getcmakediagnosticsoff:31489825
logging_disabled_new:31490726

```

</details>

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fix #435
Fix #440

Comparable to change made in https://github.com/microsoft/vscode-docker-extensibility/pull/356

### CODE REVIEW

File: src/utils/httpRequest.ts [hunk 1]
```diff
@@ -16,22 +16,26 @@ export const enum ErrorHandling {
...
-    let request = new Request(url, requestOptions ?? {});
+    if (requestOptions.body !== undefined && requestOptions.duplex === undefined) {
+        // Node's built-in fetch implementation (via undici) requires `duplex: 'half'`
+        // when sending a request body in this code path, otherwise Node throws an error.
+        requestOptions.duplex = 'half';
+    }
 
     if (signRequest) {
-        request = await signRequest(request) as Request;
+        await signRequest(requestOptions as RequestOptionsLike);
```
Comment (patverb) [inline src/utils/httpRequest.ts:35]: Would satisfies be better?

**Review by patverb — APPROVED** [review]

File: src/utils/httpRequest.ts (hunk 1 above)
Comment (bwateratmsft) [reply src/utils/httpRequest.ts:35]: `satisfies` can't be used here as `signRequest` is expecting a `RequestOptionsLike`. Basically, `satisfies` tells TS that the type is narrower than X, whereas `as` says it's wider than X.
